### ISSUE TITLE
Passkit payload read example

### ISSUE THREAD

**Issue by svmoon** [kormax/apple-enhanced-contactless-polling#3]
Hello, first I would like to add that this is great, can you add reading payloud from passkit to the examples, it would help me understand everything better

**Comment by kormax** [comment]
This repo is dedicated solely to ECP as NFC technology and not VAS as a protocol (what I assume you've meant by saying Passkit).

I have another repository linked here which is dedicated to VAS, there are also links back in that repository that can guide you to example implementations.

I've decided to keep those topics separate as to not mix up any research information. So for that info, visit [this link](https://github.com/kormax/apple-vas).

**Comment by svmoon** [comment]
I understand that you don't have an example solution for VAS that would allow this?

**Comment by kormax** [comment]
If you would have opened a link and read through it you would have found this, an example:

https://github.com/RfidResearchGroup/proxmark3/blob/master/client/src/cmdhfvas.c

If any more questions arise, I'd advice to ask them in VAS-specific repo to keep everything on topic.
