### ISSUE TITLE
More infomation regarding CATHAY?

### ISSUE THREAD

**Issue by hanpuliu-charles** [kormax/apple-enhanced-contactless-polling#5]
Hi there! Could you provide more information regarding the CATHAY protocol? Is it a protocol for transit or identification? I can't seem to find any references to it online other than in the readme of this repository. Thanks and good work on this project!

**Comment by kormax** [comment]
It's the codename for express mode polling type and protocol behavior that's used by Chinese transit cards.

Also referred to as QuickMode (old version) and GenericA (new version) in IOS source code.

This polling/behavior type is used by T-Union, SPTCC, and BMAC protocols. And it's unique in the way that it:
1) Makes your phone respond to all NFC fields, with that card preselected if no ECP is done;
2) Makes your device UID static (if other card is not selected manually);

**Comment by hanpuliu-charles** [comment]
Thanks for the infomation!

**Comment by hanpuliu-charles** [comment]
Hi @kormax,
I have another question that I hope you could clarify! I have noticed the readme in the example mentioning "broadcast frames", is this terminology only used in this project,(I can't seem to find anything related online such as in ISO14443 standard, but the description seems to be quite general)? Is this usage simply to denote a non-standard iso14443-3 frame that is sent with arbitrary data? Do you know of any usages other than with ECP protocol(and wupc for magic mifare tags)? Would be great if you could clarify these questions! Thank you very much!

**Comment by kormax** [comment]
You're correct. 

This is the term introduced by me to describe non-standards-compliant polling frames that can be used to provide contextual information about a reader inside of a polling loop (in some cases, even before proper back-and-fourth communication starts). 

It's a broader term, as it doesn't mandate any frame format. Any reader capable of broadcasting custom frames is accidentally capable of ECP and soon to be globally introduced `REDACTED` technology.

Reader manufacturers should definitely think about adding generic "broadcast frame" configuration into their hardware, to support both IOS **and** Android based devices **when** such opportunity arises.
