### ISSUE TITLE
Contacting you

### ISSUE THREAD

**Issue by Vyyer** [kormax/apple-enhanced-contactless-polling#7]
Is there a good way to reach out and discuss Apple Tap to Cash with you? We’ve done a kernel log analysis of the entire data architecture and think we can share information.

Looks like it’s repurposing Apple Pay technologies with full HCE and VAS mode turned on.

Thanks,

**Comment by kormax** [comment]
You're talking about the new IOS18 feature, right? 

Always wondered how it's working (from ECP, HCE side).

Without being able to test, I assumed that it worked similarly to NameDrop/AirDrop, with A000000858044F53452E4348 AID selected after ECP exchange (which might be different for NameDrop), where the applet exchanges a COSE-CBOR payload containing apple certificates with user info.

I'll share the means of contacting a bit later.

**Comment by Vyyer** [comment]
Tap to Cash. You can try it overseas as long as it's a US Apple ID and a US debit card loaded in the sender's phone. Full HCE routing is turned on. It's working like a payment terminal to our best knowledge.

```
default	17:19:45.802591+0300	nfcd	NFDriverSetPollingConfig:4666 Polling config is using VAS ECP
default	17:19:45.802647+0300	nfcd	NFDriverSetPollingConfig:4697 Polling cfg: A:1 B:1 F:1 15693:1 S:0 S2:0 S3:0 CustomECP:0 VAS_ECP:1 frameRF:0
default	17:19:45.802696+0300	nfcd	NFDriverSetConfiguration:5115 wantsFieldDetect=0 wantsPolling=0 wantsExpress=0 eSE=0 host=0 ceType=0, hasDiscoveryChanges=1 hasRoutingChanges=0 fullHCE=0
```

**Comment by kormax** [comment]
You sure it's correct? Mail gets rejected and no such DNS record is found.

**Comment by Vyyer** [comment]
jason@vyyer.com. Delete after you grab it plz
